cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$.WYC3Ox7TRoIATwPBmIWc.lj.DIZgLtv1McnkjsWih7Nvj4VRZxfe
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$wA95Ck8CRGH14YhCGUwSF.RnqBVf/qWykrXDBr9wwDHBh5Mp7DRQW
    tsq:
      email: tsq
      name: tsq
      password: $2b$12$DXKff0n16xpQlBN.XESDj.hhZ6ooIZWk4WdaMDCKm4JsenI337weC
preauthorized:
  emails:
  - melsby@gmail.com
